name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 1 hour
    - cron: "0 */1 * * *"
    
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: deltavenom/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

