name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 1 hour
    - cron: "0 */4 * * *"
    
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: adityanaranje/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

